### ISSUE TITLE
DieProperty.type setter issue

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#315]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

It seems the DiePropertytype setter has an issue and doesn't apply changes. 
I have used both ComponentProperty.die_property getter and clone (method) to be sure It was properly cloned but both give the same behavior.

ic_die_prop.type = definition.DieType.FLIPCHIP

![image](https://github.com/ansys/pyedb-core/assets/74993647/2cd94f60-1e1e-4026-9d8f-16f4a6722bca)

but strange thing is when I use the type getter it is here

![image](https://github.com/ansys/pyedb-core/assets/74993647/c6914abe-8f4a-4a2b-839e-3adfc3aecf50)

![image](https://github.com/ansys/pyedb-core/assets/74993647/0f01605b-7398-4ea9-a871-d24292237c97)

### 📝 Steps to reproduce

load an edb contact me if needed

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment]
@svandenb-dev The attribute of the `DiePropety` object you want to set is `die_type` not `type`. The `type` attribute doesn't exist on the `DieProperty` object. When you set it, it creates a new atribute on the `DiePropety` object called `type` because that is the standard behavior of python but it never actually gets used in the EDB. Setting the `die_type` attribute should result in the behavior you want. Thanks!
