### ISSUE TITLE
PolygonData.scale(factor, center) failing

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#462]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://github.com/user-attachments/assets/96d0a82e-9064-4ba3-babb-87bb2bcec522)

![image](https://github.com/user-attachments/assets/8676e3a1-32a5-4e00-a9ca-07c9514f09af)

![image](https://github.com/user-attachments/assets/c0f59a00-ad7e-443e-9980-3c7ff989b8e2)

![image](https://github.com/user-attachments/assets/48e5ba62-f5bb-4a3c-87a3-75746b3d7327)

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
NA
```

**Comment by drewm102** [comment]
@svandenb-dev This should be fixed in the new pyedb-core package. One thing to note is that in the pyedb-core API, the `scale(...)` API returns a new `PolygonData` that is the scaled version of the original `PolygonData` object. This is different from the behavior in the .NET API where it modifies the `PolygonData` that has the `Scale(...)` operation applied to it.
